### ***Multilayer Perceptron and Backpropagation***

In [441]:
''' Import all important library '''
import torch
import torch.nn as nn
import torch.optim as gredient
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [442]:
Device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device Name is {Device}')

Device Name is cpu


### ***Data Pipeline***

In [443]:
Transformation = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
        mean=(0.1307),
        std=(0.3181)
    )
])
'''
Compose = all number convert between (0 - 1)[pixel_num / 255]
standard division
'''

'\nCompose = all number convert between (0 - 1)[pixel_num / 255]\nstandard division\n'

In [444]:
Train_Dataset = datasets.MNIST(
    root='/Users/mahadiur/Desktop/Deep Learning Forward and Backpropagation/Data',
    train=True,
    download=True,
    transform=Transformation
)

Test_Dataset = datasets.MNIST(
    root='/Users/mahadiur/Desktop/Deep Learning Forward and Backpropagation/Data',
    train=False,
    download=True,
    transform=Transformation
)

In [445]:
print(type(Train_Dataset))

<class 'torchvision.datasets.mnist.MNIST'>


### ***Dataloader***

In [446]:
Train_Dataloader = DataLoader(
    Train_Dataset,
    batch_size=32,
    shuffle=True
)

Test_Dataloader = DataLoader(
    Test_Dataset,
    batch_size=32,
    shuffle=False
)

### ***Perceptron***

In [447]:
class Perceptron(nn.Module):
    def __init__(self, input_size):
        super(Perceptron, self).__init__()
        self.weights = nn.Parameter(torch.randn(input_size))
        self.bias = nn.Parameter(torch.randn(1))
    
    def forward(self, x):
        sumation = x @ self.weights + self.bias
        return sumation

In [448]:
''' Testing '''
input_size = 28 * 28
shuffle = torch.randn(1, input_size)

perceptron = Perceptron(
    input_size=input_size
)

output = perceptron(shuffle)
print(output)

tensor([23.0170], grad_fn=<AddBackward0>)


In [449]:
'''
Some import term for image classification:
- Batch Size (8, 32, 64, 128)
- epoch
- Step 
MNIST Dataset :
- Grayscale image 
- pixel(28 * 28)
- 60000 images in MNIST dataset
'''

'\nSome import term for image classification:\n- Batch Size (8, 32, 64, 128)\n- epoch\n- Step \nMNIST Dataset :\n- Grayscale image \n- pixel(28 * 28)\n- 60000 images in MNIST dataset\n'

### ***Activation Function***

In [450]:
'''
Activation Function: RELU (Rectified Linear Unit)
Function: max(0, z)  
'''
class RELU(nn.Module):
    def __init__(self):
        super(RELU, self).__init__()
    def forward(self, x):
        return torch.maximum(torch.tensor(0.0), x)

In [451]:
relu = RELU()
output_relu = relu(output)
print(output_relu)

tensor([23.0170], grad_fn=<MaximumBackward0>)


### ***Perceptron Hidden Layer***

In [452]:
''' Perceptron Hidden Layer '''
class Linear(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.perceptron = nn.ModuleList([
            Perceptron(input_size) for _ in range(output_size)
        ])
    def forward(self, x):
        outputs = [
            perceptron(x) for perceptron in self.perceptron
        ]
        final_output =torch.stack(outputs, dim=1)
        return final_output


# Testing
linear = Linear(input_size,10) 
output = linear(shuffle)
print(output)
print(output.shape)

tensor([[  3.0854,   9.7755, -17.4875,  28.2034,  12.2273,   3.5684, -27.1980,
         -26.6363,   2.3005,  -4.6688]], grad_fn=<StackBackward0>)
torch.Size([1, 10])


### ***Digit Classifiar betweet (1, 10)***

In [453]:
class Digitclassifiar(nn.Module):
    def __init__(self, input_size=28 * 28, output_size=10):
        super().__init__()
        self.layer1 = Linear(input_size, 512 )
        self.layer2 = Linear(512, 256)
        self.layer3 = Linear(256, 128)
        self.layer4 = Linear(128, output_size)
        self.relu = RELU()
    
    def forward(self, x):
        x = x.view(-1, input_size) # [1 ... 784]
        x = self.layer1(x) # [1 ... 640]
        x = self.relu(x) # activation function
        x = self.layer2(x) # [1...256]
        x = self.relu(x)
        x = self.layer3(x) # [1...64]
        x = self.relu(x)
        x = self.layer4(x) # [1...256]
        return x

In [454]:
Model = Digitclassifiar(input_size=28 * 28, output_size=10).to(Device)
output = Model(shuffle)
print(output.shape)
print(output)

torch.Size([1, 10])
tensor([[ 23013.1504,  61305.0859,   1404.3898, -73686.4297, -13608.5322,
         -27854.3223, -55223.2656,  -6398.3379, -25969.6191, -91086.3359]],
       grad_fn=<StackBackward0>)


### ***Run epochs***

In [455]:
optimizer = gredient.Adam(Model.parameters(), lr=0.001)
loss_function = nn.CrossEntropyLoss()
epochs = 5

for epoch in range(epochs):
    Model.train()
    current_loss = 0.0
    for batch_num, (data, target) in enumerate(Train_Dataloader):
        data, target = data.to(Device), target.to(Device)
        outputs = Model(data)
        loss = loss_function(outputs, target)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        current_loss += loss.item()
        if epoch % 100 == 0:
            print(f'Epoch {epoch + 1} / {epochs} Step [{batch_num + 1 }/ {len(Train_Dataloader)}] and Loss {loss.item():3f}')


Epoch 1 / 5 Step [1/ 1875] and Loss 79718.437500
Epoch 1 / 5 Step [2/ 1875] and Loss 73649.820312
Epoch 1 / 5 Step [3/ 1875] and Loss 68145.117188
Epoch 1 / 5 Step [4/ 1875] and Loss 50908.312500
Epoch 1 / 5 Step [5/ 1875] and Loss 41738.601562
Epoch 1 / 5 Step [6/ 1875] and Loss 46928.605469
Epoch 1 / 5 Step [7/ 1875] and Loss 32436.136719
Epoch 1 / 5 Step [8/ 1875] and Loss 39739.695312
Epoch 1 / 5 Step [9/ 1875] and Loss 39019.949219
Epoch 1 / 5 Step [10/ 1875] and Loss 28430.164062
Epoch 1 / 5 Step [11/ 1875] and Loss 28541.759766
Epoch 1 / 5 Step [12/ 1875] and Loss 37817.371094
Epoch 1 / 5 Step [13/ 1875] and Loss 30492.906250
Epoch 1 / 5 Step [14/ 1875] and Loss 34582.945312
Epoch 1 / 5 Step [15/ 1875] and Loss 24485.658203
Epoch 1 / 5 Step [16/ 1875] and Loss 24704.154297
Epoch 1 / 5 Step [17/ 1875] and Loss 21562.951172
Epoch 1 / 5 Step [18/ 1875] and Loss 17664.363281
Epoch 1 / 5 Step [19/ 1875] and Loss 18065.621094
Epoch 1 / 5 Step [20/ 1875] and Loss 24058.224609
Epoch 1 /

In [456]:
print(loss)

tensor(0.8715, grad_fn=<NllLossBackward0>)


### ***Model Accuracy***

In [457]:
Model.eval()
total = 0
Actual_val = 0

for data, target in Train_Dataloader:
    data, target = data.to(Device), target.to(Device)
    outputs = Model(data)    
    _, predict_val = torch.max(outputs.data, 1)
    total += target.size(0)
    Actual_val += (predict_val == target).sum().item()

Accuracy = 100 * Actual_val / total
print(f'Model Accuracy is {Accuracy}')


Model Accuracy is 97.58333333333333


# *Thank You*